### ISSUE TITLE
login unsuccessful

### ISSUE THREAD

**Issue by torusJKL** [cdhowie/Bitcoin-mining-proxy#15]
When opening the page on /admin a login screen is presented.

After typing the username and password like defined in config.inc.php I get redirected to the same login screen.
I can do this a infinity time without ever getting into the site.

When removing
_auth_fail();_ from _function do_admin_auth()_
the site works without any problems.

**Comment by cdhowie** [comment]
> After typing the username and password like defined in config.inc.php I get redirected to the same login screen.  I can do this a infinity time without ever getting into the site.

Try having PHP echo out your username and password both as entered and as defined in config.inc.php, and see if there are any differences.

> When removing auth_fail(); from function do_admin_auth() the site works without any problems.

Yes, but now anyone who can connect to your server can change your settings and see your passwords...

**Comment by cdhowie** [comment]
On second glance, `$_SERVER['PHP_AUTH_USER']` and `$_SERVER['PHP_AUTH_PW']` are probably not being set due to the HTTP server's configuration.  This is a config-related issue.

**Comment by raetha** [comment]
I'm new to git and not sure how to submit this as a pull request, but I found a fix for the issue. This appears to stem from using Apache with PHP in CGI mode.

To resolve the issue these lines need to be added to the .htaccess file:
<IfModule rewrite_module>
    RewriteEngine on
    RewriteRule .\* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
</IfModule>

Then in index.php and common.inc.php the check for authentication would need to be changed to:

if (!isset($_SERVER['PHP_AUTH_USER'])) {
    $ha = base64_decode(substr($_SERVER['HTTP_AUTHORIZATION'], 6));
    list($_SERVER['PHP_AUTH_USER'], $_SERVER['PHP_AUTH_PW']) = explode(':' , $ha);
    auth_fail();
}

The code could probably be made more robust in order to not bother with the rewrite if running PHP in module mode, but this definitely allowed things to load successfully and authenticate when running under a Zend installation on Windows.

Hope this info may be useful to others.

**Comment by raetha** [comment]
I've done some further work to refine this, but it may be irrelevant. It seems there is an issue running under Zend Server in CGI mode where the php-cgi.exe processes are not cleaning up correctly and eventually lock up the server. So it may be impossible to run this cleanly in CGI mode anyway which would make a fix to allow it non-useful.

**Comment by cdhowie** [comment]
Thanks for investigating this, @raetha.  Let me know if you figure out a fix for the Zend Server process issue.  I'd like to include such fixes in documentation.

**Comment by raetha** [comment]
@cdhowie, I've definitely got things working to allow the logins, but I'm not enough of a php expert to properly diagnose why the processes weren't dying off. I did a little digging and found that a common issue is sessions not closing so the processes stay open waiting for the session to end. It sounded like session_destroy() might take care of it, but I'm not sure where in your code would be appropriate to kill off the errant session.

If we do figure anything out I've forked the project and made the earlier changes in a more robust way, so can quickly submit them as a pull to help others.

**Comment by raetha** [comment]
@cdhowie, without knowing for sure how the actual pool communication part of the code works, since you are proxying I'm guessing the work request session stays open to monitor for long polls in case the client needs to stop the current getwork. In that situation I'm wondering what happens when a getwork completes successfully and/or a long poll is passed and the getwork dropped. Are you calling a session_destroy at that point? Or maybe it works correctly when the block solves without a long poll, but not when there is a long poll. The root issue definitely takes a little time to build up, so it can't be happening for every session.

If you want to help point me in the right direction I'm happy to test adding some session_destroy calls.
