### ISSUE TITLE
A table showing summary of shares submitted per pool

### ISSUE THREAD

**Issue by edgeman16** [cdhowie/Bitcoin-mining-proxy#21]
This is an enhancement/feature request, but I was wondering if there was a way to list pools and shares submitted to each pool in the past hour/hashrate.
Similar to the Worker table, but per pool instead.

**Comment by wyze** [comment]
I actually am putting the finishing touches on this right now. Double checking everything and then will be submitting a pull request for this shorty.

I currently have the shares broken out by number of accepted and rejected instead of a total amount like the worker statistics, but now wondering if I should make them consistent.

Would you rather see them broken out with a percentage, or combined total with the percentage? By percentage, I am referring to the rejected shares.

**Comment by edgeman16** [comment]
Hmm. I wouldn't mind seeing the number of rejected. Though the percentage is probably more helpful.
Good to see which pools are performing poorly.
This would be useful information for the worker table as well. Good to see which workers are getting more rejected blocks, so you can debug why it's happening.

**Comment by wyze** [comment]
Yes, I dropped the separation of accepted and rejected on the new pool status table and combined to total shares. I also replicated the code for the rejection percentage to the worker table. The tables are a bit more consistent in that sense now.
