### ISSUE TITLE
Submission Caching

### ISSUE THREAD

**Issue by nohbdy001** [cdhowie/Bitcoin-mining-proxy#34]
Some pools take longer than 2 seconds to respond to submission requests (depending on load, ddos, etc...).  This isn't a problem during a getwork request (just hop to the second pool in line), but it has been causing a high number of "rejects" for me.

I propose implementing a submission caching system.  The proxy caches the submission allowing the worker to immediately request a new piece of work.  The proxy then tries to send the solved work X times with Y timeout (say, X=10, Y=20).  Of course, this will invalidate the statistics reported on each individual miner for accepts/rejects.

Another option would be to simply increase the timeout on work submission.

**Comment by cdhowie** [comment]
> This isn't a problem during a getwork request (just hop to the second pool in line), but it has been causing a high number of "rejects" for me.

It shouldn't be causing any rejects in the proxy reports, unless the pool processes the request fine the first time but doesn't respond, and the proxy gets an error due to duplicate submission when it tries again.

> The proxy caches the submission allowing the worker to immediately request a new piece of work.

The proxy currently tries up to ten times to submit the work.  A miner should not be blocking its worker thread while this request is outstanding; if it is, that is a functional issue with the worker logic.

Having said that, the work submission timeout was really low.  I have raised this to 30 seconds (commit 20876d34); please pull and see if this fixes your issue.

**Comment by nohbdy001** [comment]
I actually made the exact same code change you made (except changed my timeout to 8) and this seemed to fix the issue for me.  It was with one particular pool that was particularly slow to respond.

I still like the idea of caching getworks and work submissions to deal with pools that are slow to respond.  But, that is a separate enhancement from this issue.  So, I'll close.

Thanks

**Comment by cdhowie** [comment]
The new C# backend does keep a queue of getwork responses (two per worker).  Implementing this in PHP would be painful, since PHP was not really designed to run things in the background.

I might implement optional submission queuing in the new backend too, at a later date.
